# Generated by Django 3.0.2 on 2020-01-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
