# Generated by Django 3.0.2 on 2020-01-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='completed',
            field=models.BooleanField(blank=True, verbose_name=False),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='course',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='name',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='question',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
