# Generated by Django 3.0.2 on 2020-01-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20200126_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='completed',
            field=models.BooleanField(blank=True),
        ),
    ]
