# Generated by Django 3.0.2 on 2020-01-26 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20200126_0146'),
        ('tickets', '0002_auto_20200126_0144'),
    ]

    operations = [
    ]
