# Generated by Django 3.0.2 on 2020-01-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20200126_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='course',
            field=models.CharField(choices=[('206', '206'), ('207', '207'), ('208', '208'), ('209', '209')], max_length=8),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='name',
            field=models.CharField(max_length=15, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='question',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
