# Generated by Django 3.0.2 on 2020-01-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_merge_20200126_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='peer',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
