# Generated by Django 3.0.2 on 2020-01-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20200126_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='course',
            field=models.CharField(choices=[('201', '201'), ('202', '202')], max_length=8),
        ),
    ]
