# Generated by Django 3.0.2 on 2020-01-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20200125_2344'),
        ('tickets', '0010_auto_20200126_1603'),
    ]

    operations = [
    ]
